#!/bin/sh

script_dir=/usr/sbin

case "$1" in
  start)
    echo "Loading scull module..."
    ${script_dir}/module_load scull 0 3
    ;;
  stop)
    echo "Unloading scull module..."
    ${script_dir}/module_unload scull 0 3
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac
exit 0

